services:
  app:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge